const SEND_FILE_CONFIRM_EVENT_NAME = 'sendFileConfirm';
const SEND_FILE_ACCEPT_EVENT_NAME = 'sendFileAccept';
const SEND_FILE_REJECT_EVENT_NAME = 'sendFileReject';
const SEND_FILE_CHUNK_EVENT_NAME = 'sendFileChunk';
const FILE_UPLOAD_EVENT_NAME = 'fileUpload';
const FILE_DOWNLOAD_CONFIRM_EVENT_NAME = 'fileDownloadConfirm';
const FILE_DOWNLOAD_START_EVENT_NAME = 'fileDownloadStart';
const CHUNK_SIZE = 45 * 1024;
module.exports = {
    SEND_FILE_CONFIRM_EVENT_NAME,
    SEND_FILE_ACCEPT_EVENT_NAME,
    SEND_FILE_REJECT_EVENT_NAME,
    SEND_FILE_CHUNK_EVENT_NAME,
    FILE_UPLOAD_EVENT_NAME,
    FILE_DOWNLOAD_CONFIRM_EVENT_NAME,
    FILE_DOWNLOAD_START_EVENT_NAME,
    CHUNK_SIZE,
}